BEGIN;

ALTER TABLE contatos
  ADD COLUMN IF NOT EXISTS consentimento_tratamento_dados BOOLEAN,
  ADD COLUMN IF NOT EXISTS consentimento_whatsapp BOOLEAN,
  ADD COLUMN IF NOT EXISTS consentimento_ligacoes BOOLEAN,
  ADD COLUMN IF NOT EXISTS consentimentos_atualizados_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS origem_atual VARCHAR(200),
  ADD COLUMN IF NOT EXISTS status_contato VARCHAR(30),
  ADD COLUMN IF NOT EXISTS bloqueado_para_mensagens BOOLEAN,
  ADD COLUMN IF NOT EXISTS excluido_logicamente BOOLEAN,
  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE contatos
SET
  consentimento_tratamento_dados = COALESCE(
    consentimento_tratamento_dados,
    consentimento_armazenamento
  ),
  consentimento_whatsapp = COALESCE(
    consentimento_whatsapp,
    consentimento_mensagens
  ),
  consentimentos_atualizados_em = COALESCE(
    consentimentos_atualizados_em,
    consentimento_mensagens_em,
    consentimento_armazenamento_em,
    criado_em
  ),
  origem_atual = COALESCE(origem_atual, 'Cadastro legado'),
  status_contato = COALESCE(status_contato, 'ativo'),
  bloqueado_para_mensagens = COALESCE(
    bloqueado_para_mensagens,
    CASE
      WHEN COALESCE(consentimento_whatsapp, consentimento_mensagens) IS TRUE
        THEN FALSE
      ELSE TRUE
    END
  ),
  excluido_logicamente = COALESCE(excluido_logicamente, FALSE);

ALTER TABLE contatos
  ALTER COLUMN bloqueado_para_mensagens SET DEFAULT FALSE,
  ALTER COLUMN bloqueado_para_mensagens SET NOT NULL,
  ALTER COLUMN excluido_logicamente SET DEFAULT FALSE,
  ALTER COLUMN excluido_logicamente SET NOT NULL;

CREATE TABLE IF NOT EXISTS consentimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato_id BIGINT NOT NULL REFERENCES contatos(id),
  tipo VARCHAR(50) NOT NULL,
  resposta BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  canal VARCHAR(50) NOT NULL,
  origem_registro VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revogado_em TIMESTAMPTZ,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT consentimentos_tipo_valido CHECK (
    tipo IN ('tratamento_dados', 'mensagens_whatsapp', 'ligacoes')
  ),
  CONSTRAINT consentimentos_canal_valido CHECK (
    canal IN (
      'formulario_publico',
      'cadastro_manual',
      'importacao',
      'migracao',
      'whatsapp',
      'telefone',
      'outro'
    )
  ),
  CONSTRAINT consentimentos_origem_registro_valida CHECK (
    origem_registro IN (
      'resposta_expressa',
      'migracao_legado',
      'revogacao',
      'atualizacao'
    )
  ),
  CONSTRAINT consentimentos_revogacao_coerente CHECK (
    ativo = FALSE OR revogado_em IS NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS consentimentos_contato_tipo_ativo_unico
  ON consentimentos (contato_id, tipo)
  WHERE ativo = TRUE;

CREATE INDEX IF NOT EXISTS consentimentos_contato_id_indice
  ON consentimentos (contato_id);

CREATE INDEX IF NOT EXISTS consentimentos_criado_em_indice
  ON consentimentos (criado_em DESC);

CREATE INDEX IF NOT EXISTS contatos_consentimento_whatsapp_indice
  ON contatos (consentimento_whatsapp);

CREATE INDEX IF NOT EXISTS contatos_consentimento_ligacoes_indice
  ON contatos (consentimento_ligacoes);

CREATE INDEX IF NOT EXISTS contatos_origem_atual_indice
  ON contatos (LOWER(origem_atual));

CREATE INDEX IF NOT EXISTS contatos_status_contato_indice
  ON contatos (LOWER(status_contato));

UPDATE consentimentos
SET versao_texto = 'legado_v1'
WHERE origem_registro = 'migracao_legado'
  AND versao_texto = 'legado_sem_versao'
  AND texto_apresentado = 'Texto apresentado não registrado pelo sistema legado.';

INSERT INTO consentimentos (
  contato_id,
  tipo,
  resposta,
  texto_apresentado,
  versao_texto,
  canal,
  origem_registro,
  criado_em,
  ativo
)
SELECT
  contato.id,
  'tratamento_dados',
  contato.consentimento_armazenamento,
  'Texto apresentado não registrado pelo sistema legado.',
  'legado_v1',
  'migracao',
  'migracao_legado',
  COALESCE(contato.consentimento_armazenamento_em, contato.criado_em),
  TRUE
FROM contatos AS contato
WHERE NOT EXISTS (
  SELECT 1
  FROM consentimentos AS consentimento
  WHERE consentimento.contato_id = contato.id
    AND consentimento.tipo = 'tratamento_dados'
    AND consentimento.ativo = TRUE
);

INSERT INTO consentimentos (
  contato_id,
  tipo,
  resposta,
  texto_apresentado,
  versao_texto,
  canal,
  origem_registro,
  criado_em,
  ativo
)
SELECT
  contato.id,
  'mensagens_whatsapp',
  contato.consentimento_mensagens,
  'Texto apresentado não registrado pelo sistema legado.',
  'legado_v1',
  'migracao',
  'migracao_legado',
  COALESCE(
    contato.consentimento_mensagens_em,
    contato.consentimento_armazenamento_em,
    contato.criado_em
  ),
  TRUE
FROM contatos AS contato
WHERE NOT EXISTS (
  SELECT 1
  FROM consentimentos AS consentimento
  WHERE consentimento.contato_id = contato.id
    AND consentimento.tipo = 'mensagens_whatsapp'
    AND consentimento.ativo = TRUE
);

COMMIT;
