CREATE TABLE origens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT origens_nome_nao_vazio CHECK (
    LENGTH(TRIM(nome)) >= 2
  ),
  CONSTRAINT origens_slug_formato CHECK (
    slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  CONSTRAINT origens_tipo_nao_vazio CHECK (
    LENGTH(TRIM(tipo)) >= 2
  )
);

CREATE UNIQUE INDEX origens_slug_unico
  ON origens (LOWER(slug));

CREATE TRIGGER origens_atualizar_data
BEFORE UPDATE ON origens
FOR EACH ROW
EXECUTE FUNCTION atualizar_data_modificacao();

INSERT INTO origens (nome, slug, tipo, ativa)
VALUES ('Cadastro legado', 'cadastro-legado', 'legado', TRUE);

ALTER TABLE contatos
  ADD COLUMN origem_id BIGINT;

ALTER TABLE contatos
  ADD CONSTRAINT contatos_origem_id_fkey
  FOREIGN KEY (origem_id)
  REFERENCES origens(id);

UPDATE contatos
SET origem_id = (
  SELECT origem.id
  FROM origens AS origem
  WHERE origem.slug = 'cadastro-legado'
)
WHERE origem_atual = 'Cadastro legado'
  AND origem_id IS NULL;

CREATE INDEX contatos_origem_id_indice
  ON contatos (origem_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM contatos
    WHERE origem_atual = 'Cadastro legado'
      AND origem_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Nem todos os contatos legados receberam origem_id.';
  END IF;
END;
$$;
