CREATE TABLE historico_contatos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato_id BIGINT NOT NULL,
  tipo_evento VARCHAR(50) NOT NULL,
  dados_anteriores JSONB,
  dados_novos JSONB,
  origem_id BIGINT,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_contatos_contato_id_fkey
    FOREIGN KEY (contato_id)
    REFERENCES contatos(id),
  CONSTRAINT historico_contatos_origem_id_fkey
    FOREIGN KEY (origem_id)
    REFERENCES origens(id),
  CONSTRAINT historico_contatos_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES usuarios(id)
    ON DELETE SET NULL,
  CONSTRAINT historico_contatos_tipo_evento_nao_vazio CHECK (
    LENGTH(TRIM(tipo_evento)) >= 2
  ),
  CONSTRAINT historico_contatos_possui_dados CHECK (
    dados_anteriores IS NOT NULL OR dados_novos IS NOT NULL
  )
);

CREATE INDEX historico_contatos_contato_id_indice
  ON historico_contatos (contato_id);

CREATE INDEX historico_contatos_criado_em_indice
  ON historico_contatos (criado_em DESC);

CREATE INDEX historico_contatos_origem_id_indice
  ON historico_contatos (origem_id);
