INSERT INTO origens (nome, slug, tipo, ativa)
VALUES ('Formulário público', 'formulario-publico', 'formulario', TRUE);

CREATE TABLE textos_formulario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  versao VARCHAR(100) NOT NULL,
  texto TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT textos_formulario_tipo_valido CHECK (
    tipo IN ('aviso_privacidade', 'mensagens', 'ligacoes')
  ),
  CONSTRAINT textos_formulario_versao_nao_vazia CHECK (
    LENGTH(TRIM(versao)) >= 2
  ),
  CONSTRAINT textos_formulario_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto)) >= 10
  ),
  CONSTRAINT textos_formulario_tipo_versao_unicos UNIQUE (tipo, versao)
);

CREATE UNIQUE INDEX textos_formulario_tipo_ativo_unico
  ON textos_formulario (tipo)
  WHERE ativo = TRUE;

CREATE TRIGGER textos_formulario_atualizar_data
BEFORE UPDATE ON textos_formulario
FOR EACH ROW
EXECUTE FUNCTION atualizar_data_modificacao();

INSERT INTO textos_formulario (tipo, versao, texto)
VALUES
  (
    'aviso_privacidade',
    'aviso_privacidade_v1',
    'Li o Aviso de Privacidade e autorizo o tratamento dos dados informados para participação no projeto A Voz do Bairro.'
  ),
  (
    'mensagens',
    'mensagens_v1',
    'Autorizo o recebimento de futuras mensagens sobre ações sociais, projetos comunitários, pesquisas, conteúdos políticos, eventos e iniciativas relacionadas à melhoria dos bairros.'
  ),
  (
    'ligacoes',
    'ligacoes_v1',
    'Autorizo o recebimento de futuras ligações sobre ações sociais, projetos comunitários, pesquisas, conteúdos políticos, eventos e iniciativas relacionadas à melhoria dos bairros.'
  );

CREATE TABLE aceites_privacidade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato_id BIGINT NOT NULL,
  aceito BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  origem_id BIGINT NOT NULL,
  canal VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT aceites_privacidade_contato_id_fkey
    FOREIGN KEY (contato_id)
    REFERENCES contatos(id),
  CONSTRAINT aceites_privacidade_origem_id_fkey
    FOREIGN KEY (origem_id)
    REFERENCES origens(id),
  CONSTRAINT aceites_privacidade_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES usuarios(id)
    ON DELETE SET NULL,
  CONSTRAINT aceites_privacidade_aceite_obrigatorio CHECK (aceito = TRUE),
  CONSTRAINT aceites_privacidade_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto_apresentado)) >= 10
  ),
  CONSTRAINT aceites_privacidade_canal_valido CHECK (
    canal IN ('formulario_publico', 'cadastro_manual', 'outro')
  )
);

CREATE UNIQUE INDEX aceites_privacidade_resposta_identica_unica
  ON aceites_privacidade (
    contato_id,
    versao_texto,
    origem_id,
    canal,
    MD5(texto_apresentado)
  )
  WHERE aceito = TRUE;

CREATE INDEX aceites_privacidade_contato_id_indice
  ON aceites_privacidade (contato_id);

CREATE INDEX aceites_privacidade_criado_em_indice
  ON aceites_privacidade (criado_em DESC);

ALTER TABLE consentimentos
  ADD COLUMN estado VARCHAR(30),
  ADD COLUMN origem_id BIGINT;

ALTER TABLE consentimentos
  DROP CONSTRAINT consentimentos_tipo_valido;

ALTER TABLE consentimentos
  ADD CONSTRAINT consentimentos_tipo_valido CHECK (
    tipo IN (
      'tratamento_dados',
      'mensagens_whatsapp',
      'mensagens',
      'ligacoes'
    )
  ),
  ADD CONSTRAINT consentimentos_estado_valido CHECK (
    estado IS NULL
    OR estado IN ('autorizado', 'recusado', 'revogado')
  ),
  ADD CONSTRAINT consentimentos_origem_id_fkey
    FOREIGN KEY (origem_id)
    REFERENCES origens(id);

CREATE INDEX consentimentos_origem_id_indice
  ON consentimentos (origem_id);

CREATE INDEX consentimentos_estado_indice
  ON consentimentos (estado);
