ALTER TABLE contatos
  ALTER COLUMN nome DROP NOT NULL,
  ALTER COLUMN bairro DROP NOT NULL,
  ALTER COLUMN problema DROP NOT NULL;

CREATE TABLE importacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_arquivo VARCHAR(255) NOT NULL,
  formato VARCHAR(10) NOT NULL,
  origem_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pre_visualizada',
  total_recebido INTEGER NOT NULL DEFAULT 0,
  relatorio JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmado_em TIMESTAMPTZ,
  CONSTRAINT importacoes_formato_valido CHECK (formato IN ('csv', 'xlsx')),
  CONSTRAINT importacoes_status_valido CHECK (
    status IN ('pre_visualizada', 'processando', 'concluida', 'falhou')
  ),
  CONSTRAINT importacoes_origem_id_fkey FOREIGN KEY (origem_id) REFERENCES origens(id),
  CONSTRAINT importacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE importacao_linhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacao_id BIGINT NOT NULL,
  numero_linha INTEGER NOT NULL,
  dados JSONB NOT NULL,
  valida BOOLEAN NOT NULL,
  erro_validacao TEXT,
  resultado VARCHAR(30) NOT NULL DEFAULT 'pendente',
  contato_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT importacao_linhas_importacao_id_fkey
    FOREIGN KEY (importacao_id) REFERENCES importacoes(id) ON DELETE CASCADE,
  CONSTRAINT importacao_linhas_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES contatos(id),
  CONSTRAINT importacao_linhas_resultado_valido CHECK (
    resultado IN (
      'pendente', 'criado', 'complementado', 'ignorado',
      'duplicado', 'invalido', 'erro'
    )
  ),
  CONSTRAINT importacao_linhas_numero_unico UNIQUE (importacao_id, numero_linha)
);

CREATE INDEX importacoes_criado_em_indice ON importacoes (criado_em DESC);
CREATE INDEX importacao_linhas_importacao_id_indice ON importacao_linhas (importacao_id);
CREATE INDEX importacao_linhas_contato_id_indice ON importacao_linhas (contato_id);
