ALTER TABLE public.modelos_mensagem
  ADD COLUMN IF NOT EXISTS meta_template_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS meta_componentes JSONB,
  ADD COLUMN IF NOT EXISTS meta_status_oficial VARCHAR(50),
  ADD COLUMN IF NOT EXISTS meta_origem VARCHAR(20) NOT NULL DEFAULT 'interno',
  ADD COLUMN IF NOT EXISTS meta_submetido_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_sincronizado_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS meta_configuracao_envio JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.modelos_mensagem
  DROP CONSTRAINT IF EXISTS modelos_mensagem_meta_status_valido;

ALTER TABLE public.modelos_mensagem
  ADD CONSTRAINT modelos_mensagem_meta_status_valido
    CHECK (meta_status IN (
      'rascunho', 'em_analise', 'aprovado', 'rejeitado', 'indisponivel'
    )),
  ADD CONSTRAINT modelos_mensagem_meta_origem_valida
    CHECK (meta_origem IN ('interno', 'meta')),
  ADD CONSTRAINT modelos_mensagem_meta_componentes_objeto_valido
    CHECK (meta_componentes IS NULL OR jsonb_typeof(meta_componentes) = 'array'),
  ADD CONSTRAINT modelos_mensagem_meta_configuracao_envio_objeto_valido
    CHECK (jsonb_typeof(meta_configuracao_envio) = 'object');

CREATE UNIQUE INDEX IF NOT EXISTS modelos_mensagem_meta_template_id_unico
  ON public.modelos_mensagem (meta_template_id)
  WHERE meta_template_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS modelos_mensagem_meta_sincronizacao_indice
  ON public.modelos_mensagem (meta_sincronizado_em DESC)
  WHERE meta_template_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.historico_modelos_mensagem_meta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id BIGINT NOT NULL REFERENCES public.modelos_mensagem(id),
  meta_template_id VARCHAR(100),
  acao VARCHAR(40) NOT NULL,
  status_anterior VARCHAR(50),
  status_novo VARCHAR(50),
  origem VARCHAR(30) NOT NULL,
  usuario_id BIGINT REFERENCES public.usuarios(id),
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_modelos_mensagem_meta_acao_valida CHECK (
    acao IN ('rascunho_criado', 'rascunho_atualizado', 'configuracao_envio', 'submissao',
      'sincronizacao', 'vinculo_inicial')
  ),
  CONSTRAINT historico_modelos_mensagem_meta_origem_valida CHECK (
    origem IN ('sistema', 'api_meta', 'sincronizacao_meta')
  ),
  CONSTRAINT historico_modelos_mensagem_meta_detalhes_validos CHECK (
    jsonb_typeof(detalhes) = 'object'
  )
);

CREATE INDEX IF NOT EXISTS historico_modelos_mensagem_meta_modelo_indice
  ON public.historico_modelos_mensagem_meta (modelo_id, criado_em DESC);
