-- Criação completa do banco de dados do projeto A Voz do Bairro.
-- Representa o estado estrutural atual e adiciona somente a base aprovada
-- para uma futura integração com o ManyChat.
--
-- USO EXCLUSIVO EM BANCO POSTGRESQL VAZIO.
-- Este arquivo falha de propósito se encontrar alguma tabela do projeto.
-- Para atualizar a estrutura, crie antes um backup completo e validado,
-- recrie um banco vazio com este arquivo e restaure somente os dados aprovados.

BEGIN;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;
SET check_function_bodies = FALSE;
SET client_min_messages = WARNING;

DO $$
DECLARE
  objeto_existente TEXT;
BEGIN
  SELECT classe.relname
  INTO objeto_existente
  FROM pg_catalog.pg_class AS classe
  INNER JOIN pg_catalog.pg_namespace AS namespace
    ON namespace.oid = classe.relnamespace
  WHERE namespace.nspname = 'public'
    AND classe.relname IN (
      'aceites_privacidade',
      'backups_banco',
      'bairros',
      'consentimentos',
      'contatos',
      'historico_contatos',
      'importacao_linhas',
      'importacoes',
      'origens',
      'campanhas',
      'campanha_contatos',
      'envios_campanha',
      'respostas_campanha',
      'eventos_manychat',
      'eventos',
      'historico_eventos',
      'contato_eventos',
      'solicitacoes_exclusao',
      'sincronizacoes_manychat',
      'tentativas_login',
      'textos_formulario',
      'usuarios'
    )
  LIMIT 1;

  IF objeto_existente IS NOT NULL THEN
    RAISE EXCEPTION
      'Execução recusada: o banco já possui a estrutura do projeto (%). Este arquivo exige um banco vazio.',
      objeto_existente;
  END IF;

  IF to_regprocedure('public.atualizar_data_modificacao()') IS NOT NULL THEN
    RAISE EXCEPTION
      'Execução recusada: a função atualizar_data_modificacao já existe. Use um banco vazio.';
  END IF;
END;
$$;

CREATE FUNCTION public.atualizar_data_modificacao()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.atualizado_em = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE public.bairros (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bairros_pkey PRIMARY KEY (id),
  CONSTRAINT bairros_nome_unico UNIQUE (nome),
  CONSTRAINT bairros_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2)
);

CREATE TABLE public.origens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT origens_pkey PRIMARY KEY (id),
  CONSTRAINT origens_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT origens_slug_formato CHECK (
    slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
  ),
  CONSTRAINT origens_tipo_nao_vazio CHECK (LENGTH(TRIM(tipo)) >= 2)
);

CREATE TABLE public.usuarios (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  perfil VARCHAR(30) NOT NULL DEFAULT 'operador',
  tentativas_login_falhas INTEGER NOT NULL DEFAULT 0,
  bloqueado_ate TIMESTAMPTZ,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_email_nao_vazio CHECK (LENGTH(TRIM(email)) >= 5),
  CONSTRAINT usuarios_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT usuarios_perfil_valido CHECK (
    perfil IN ('administrador', 'operador')
  ),
  CONSTRAINT usuarios_tentativas_login_validas CHECK (
    tentativas_login_falhas >= 0
  )
);

CREATE TABLE public.eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  motivo TEXT NOT NULL,
  data_inicial DATE NOT NULL,
  data_final DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'rascunho',
  criado_por_usuario_id BIGINT NOT NULL,
  atualizado_por_usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT eventos_pkey PRIMARY KEY (id),
  CONSTRAINT eventos_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT eventos_motivo_nao_vazio CHECK (LENGTH(TRIM(motivo)) >= 2),
  CONSTRAINT eventos_periodo_valido CHECK (data_final >= data_inicial),
  CONSTRAINT eventos_status_valido CHECK (
    status IN ('rascunho', 'ativo', 'encerrado')
  )
);

CREATE TABLE public.historico_eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  evento_id BIGINT NOT NULL,
  tipo_acao VARCHAR(30) NOT NULL,
  dados_anteriores JSONB,
  dados_novos JSONB,
  usuario_id BIGINT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_eventos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_eventos_acao_valida CHECK (
    tipo_acao IN ('criacao', 'edicao', 'ativacao', 'encerramento')
  )
);

CREATE TABLE public.contatos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150),
  telefone VARCHAR(30) NOT NULL,
  telefone_normalizado VARCHAR(20) NOT NULL,
  bairro VARCHAR(150),
  problema VARCHAR(500),
  consentimento_armazenamento BOOLEAN NOT NULL,
  consentimento_mensagens BOOLEAN NOT NULL DEFAULT FALSE,
  consentimento_armazenamento_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consentimento_mensagens_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consentimento_tratamento_dados BOOLEAN,
  consentimento_whatsapp BOOLEAN,
  consentimento_ligacoes BOOLEAN,
  consentimentos_atualizados_em TIMESTAMPTZ,
  origem_atual VARCHAR(200),
  status_contato VARCHAR(30),
  bloqueado_para_mensagens BOOLEAN NOT NULL DEFAULT FALSE,
  origem_id BIGINT,
  idade SMALLINT,
  descricao_problema TEXT,
  bloqueado_para_ligacoes BOOLEAN NOT NULL DEFAULT FALSE,
  bloqueado_para_campanhas BOOLEAN NOT NULL DEFAULT FALSE,
  manychat_contact_id VARCHAR(255),
  CONSTRAINT contatos_pkey PRIMARY KEY (id),
  CONSTRAINT contatos_bairro_nao_vazio CHECK (
    LENGTH(TRIM(bairro)) >= 2
  ),
  CONSTRAINT contatos_consentimento_armazenamento_obrigatorio CHECK (
    consentimento_armazenamento = TRUE
  ),
  CONSTRAINT contatos_data_consentimento_mensagens CHECK (
    (consentimento_mensagens = TRUE AND consentimento_mensagens_em IS NOT NULL)
    OR
    (consentimento_mensagens = FALSE AND consentimento_mensagens_em IS NULL)
  ),
  CONSTRAINT contatos_idade_valida CHECK (
    idade IS NULL OR idade BETWEEN 16 AND 120
  ),
  CONSTRAINT contatos_manychat_contact_id_nao_vazio CHECK (
    manychat_contact_id IS NULL OR LENGTH(TRIM(manychat_contact_id)) >= 1
  ),
  CONSTRAINT contatos_nome_nao_vazio CHECK (
    LENGTH(TRIM(nome)) >= 2
  ),
  CONSTRAINT contatos_problema_nao_vazio CHECK (
    LENGTH(TRIM(problema)) >= 3
  ),
  CONSTRAINT contatos_telefone_nao_vazio CHECK (
    LENGTH(TRIM(telefone)) >= 8
  ),
  CONSTRAINT contatos_telefone_normalizado_apenas_numeros CHECK (
    telefone_normalizado ~ '^[0-9]+$'
  ),
  CONSTRAINT contatos_telefone_normalizado_tamanho CHECK (
    LENGTH(telefone_normalizado) BETWEEN 10 AND 15
  )
);

CREATE TABLE public.contato_eventos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  contato_id BIGINT NOT NULL,
  evento_id BIGINT NOT NULL,
  cadastrado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contato_eventos_pkey PRIMARY KEY (id),
  CONSTRAINT contato_eventos_contato_evento_unicos UNIQUE (contato_id, evento_id)
);

CREATE TABLE public.consentimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT,
  contato_id_original BIGINT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  resposta BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  canal VARCHAR(50) NOT NULL,
  origem_registro VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revogado_em TIMESTAMPTZ,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  estado VARCHAR(30),
  origem_id BIGINT,
  motivo_revogacao VARCHAR(500),
  registro_anterior_id BIGINT,
  CONSTRAINT consentimentos_pkey PRIMARY KEY (id),
  CONSTRAINT consentimentos_canal_valido CHECK (
    canal IN (
      'formulario_publico',
      'cadastro_manual',
      'area_administrativa',
      'importacao',
      'migracao',
      'whatsapp',
      'telefone',
      'outro'
    )
  ),
  CONSTRAINT consentimentos_estado_valido CHECK (
    estado IS NULL OR estado IN ('autorizado', 'recusado', 'revogado')
  ),
  CONSTRAINT consentimentos_motivo_revogacao_valido CHECK (
    motivo_revogacao IS NULL
    OR LENGTH(TRIM(motivo_revogacao)) BETWEEN 1 AND 500
  ),
  CONSTRAINT consentimentos_origem_registro_valida CHECK (
    origem_registro IN (
      'resposta_expressa',
      'migracao_legado',
      'revogacao',
      'atualizacao'
    )
  ),
  CONSTRAINT consentimentos_revogacao_coerente CHECK (
    ativo = FALSE OR revogado_em IS NULL
  ),
  CONSTRAINT consentimentos_tipo_valido CHECK (
    tipo IN (
      'tratamento_dados',
      'mensagens_whatsapp',
      'mensagens',
      'ligacoes'
    )
  )
);

CREATE TABLE public.solicitacoes_exclusao (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  contato_id BIGINT,
  contato_id_original BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente',
  solicitada_por_usuario_id BIGINT NOT NULL,
  analisada_por_usuario_id BIGINT,
  observacoes TEXT,
  solicitada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  analisada_em TIMESTAMPTZ,
  executada_em TIMESTAMPTZ,
  CONSTRAINT solicitacoes_exclusao_pkey PRIMARY KEY (id),
  CONSTRAINT solicitacoes_exclusao_status_valido CHECK (
    status IN ('pendente', 'aprovada', 'rejeitada')
  ),
  CONSTRAINT solicitacoes_exclusao_analise_coerente CHECK (
    (status = 'pendente' AND analisada_por_usuario_id IS NULL AND analisada_em IS NULL)
    OR
    (status IN ('aprovada', 'rejeitada') AND analisada_por_usuario_id IS NOT NULL AND analisada_em IS NOT NULL)
  ),
  CONSTRAINT solicitacoes_exclusao_execucao_coerente CHECK (
    executada_em IS NULL OR status = 'aprovada'
  )
);

CREATE TABLE public.aceites_privacidade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT NOT NULL,
  aceito BOOLEAN NOT NULL,
  texto_apresentado TEXT NOT NULL,
  versao_texto VARCHAR(100) NOT NULL,
  origem_id BIGINT NOT NULL,
  canal VARCHAR(50) NOT NULL,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT aceites_privacidade_pkey PRIMARY KEY (id),
  CONSTRAINT aceites_privacidade_aceite_obrigatorio CHECK (aceito = TRUE),
  CONSTRAINT aceites_privacidade_canal_valido CHECK (
    canal IN ('formulario_publico', 'cadastro_manual', 'outro')
  ),
  CONSTRAINT aceites_privacidade_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto_apresentado)) >= 10
  )
);

CREATE TABLE public.historico_contatos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  contato_id BIGINT NOT NULL,
  tipo_evento VARCHAR(50) NOT NULL,
  dados_anteriores JSONB,
  dados_novos JSONB,
  origem_id BIGINT,
  registrado_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT historico_contatos_pkey PRIMARY KEY (id),
  CONSTRAINT historico_contatos_possui_dados CHECK (
    dados_anteriores IS NOT NULL OR dados_novos IS NOT NULL
  ),
  CONSTRAINT historico_contatos_tipo_evento_nao_vazio CHECK (
    LENGTH(TRIM(tipo_evento)) >= 2
  )
);

CREATE TABLE public.importacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nome_arquivo VARCHAR(255) NOT NULL,
  formato VARCHAR(10) NOT NULL,
  origem_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pre_visualizada',
  total_recebido INTEGER NOT NULL DEFAULT 0,
  relatorio JSONB,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmado_em TIMESTAMPTZ,
  CONSTRAINT importacoes_pkey PRIMARY KEY (id),
  CONSTRAINT importacoes_formato_valido CHECK (
    formato IN ('csv', 'xlsx')
  ),
  CONSTRAINT importacoes_status_valido CHECK (
    status IN ('pre_visualizada', 'processando', 'concluida', 'falhou')
  )
);

CREATE TABLE public.importacao_linhas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  importacao_id BIGINT NOT NULL,
  numero_linha INTEGER NOT NULL,
  dados JSONB NOT NULL,
  valida BOOLEAN NOT NULL,
  erro_validacao TEXT,
  resultado VARCHAR(30) NOT NULL DEFAULT 'pendente',
  contato_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT importacao_linhas_pkey PRIMARY KEY (id),
  CONSTRAINT importacao_linhas_numero_unico UNIQUE (importacao_id, numero_linha),
  CONSTRAINT importacao_linhas_resultado_valido CHECK (
    resultado IN (
      'pendente',
      'criado',
      'complementado',
      'ignorado',
      'duplicado',
      'invalido',
      'erro'
    )
  )
);

CREATE TABLE public.tentativas_login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  usuario_id BIGINT,
  email_informado VARCHAR(200) NOT NULL,
  endereco_ip VARCHAR(64) NOT NULL,
  agente_usuario VARCHAR(500),
  sucesso BOOLEAN NOT NULL,
  motivo VARCHAR(40) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tentativas_login_pkey PRIMARY KEY (id),
  CONSTRAINT tentativas_login_motivo_valido CHECK (
    motivo IN (
      'sucesso',
      'credenciais_invalidas',
      'usuario_inativo',
      'conta_bloqueada'
    )
  )
);

CREATE TABLE public.backups_banco (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  usuario_id BIGINT,
  status VARCHAR(20) NOT NULL DEFAULT 'processando',
  nome_arquivo VARCHAR(255),
  formato VARCHAR(20) NOT NULL DEFAULT 'custom',
  tamanho_bytes BIGINT,
  sha256 CHAR(64),
  mensagem_erro VARCHAR(1000),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  concluido_em TIMESTAMPTZ,
  CONSTRAINT backups_banco_pkey PRIMARY KEY (id),
  CONSTRAINT backups_banco_status_valido CHECK (
    status IN ('processando', 'concluido', 'falhou')
  ),
  CONSTRAINT backups_banco_formato_valido CHECK (formato = 'custom'),
  CONSTRAINT backups_banco_tamanho_valido CHECK (
    tamanho_bytes IS NULL OR tamanho_bytes >= 0
  ),
  CONSTRAINT backups_banco_sha256_valido CHECK (
    sha256 IS NULL OR sha256 ~ '^[A-F0-9]{64}$'
  ),
  CONSTRAINT backups_banco_conclusao_coerente CHECK (
    (status = 'processando' AND concluido_em IS NULL)
    OR
    (status IN ('concluido', 'falhou') AND concluido_em IS NOT NULL)
  )
);

CREATE TABLE public.textos_formulario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tipo VARCHAR(50) NOT NULL,
  versao VARCHAR(100) NOT NULL,
  texto TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT textos_formulario_pkey PRIMARY KEY (id),
  CONSTRAINT textos_formulario_texto_nao_vazio CHECK (
    LENGTH(TRIM(texto)) >= 10
  ),
  CONSTRAINT textos_formulario_tipo_valido CHECK (
    tipo IN ('aviso_privacidade', 'mensagens', 'ligacoes')
  ),
  CONSTRAINT textos_formulario_versao_nao_vazia CHECK (
    LENGTH(TRIM(versao)) >= 2
  ),
  CONSTRAINT textos_formulario_tipo_versao_unicos UNIQUE (tipo, versao)
);

CREATE TABLE public.campanhas (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT,
  manychat_flow_id VARCHAR(255),
  status VARCHAR(30) NOT NULL DEFAULT 'rascunho',
  criado_por_usuario_id BIGINT NOT NULL,
  agendada_em TIMESTAMPTZ,
  iniciada_em TIMESTAMPTZ,
  encerrada_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanhas_pkey PRIMARY KEY (id),
  CONSTRAINT campanhas_nome_nao_vazio CHECK (LENGTH(TRIM(nome)) >= 2),
  CONSTRAINT campanhas_manychat_flow_id_nao_vazio CHECK (
    manychat_flow_id IS NULL OR LENGTH(TRIM(manychat_flow_id)) >= 1
  ),
  CONSTRAINT campanhas_status_valido CHECK (
    status IN ('rascunho', 'agendada', 'ativa', 'pausada', 'concluida', 'cancelada')
  )
);

CREATE TABLE public.campanha_contatos (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  campanha_id BIGINT NOT NULL,
  contato_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'elegivel',
  incluido_por_usuario_id BIGINT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT campanha_contatos_pkey PRIMARY KEY (id),
  CONSTRAINT campanha_contatos_campanha_contato_unicos UNIQUE (
    campanha_id,
    contato_id
  ),
  CONSTRAINT campanha_contatos_status_valido CHECK (
    status IN (
      'elegivel',
      'em_fila',
      'enviado',
      'entregue',
      'lido',
      'respondido',
      'recusado',
      'bloqueado',
      'concluido',
      'erro'
    )
  )
);

CREATE TABLE public.envios_campanha (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  campanha_contato_id BIGINT NOT NULL,
  numero_tentativa INTEGER NOT NULL DEFAULT 1,
  status VARCHAR(30) NOT NULL DEFAULT 'pendente',
  manychat_message_id VARCHAR(255),
  mensagem_erro TEXT,
  solicitado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enviado_em TIMESTAMPTZ,
  entregue_em TIMESTAMPTZ,
  lido_em TIMESTAMPTZ,
  respondido_em TIMESTAMPTZ,
  CONSTRAINT envios_campanha_pkey PRIMARY KEY (id),
  CONSTRAINT envios_campanha_tentativa_unica UNIQUE (
    campanha_contato_id,
    numero_tentativa
  ),
  CONSTRAINT envios_campanha_numero_tentativa_valido CHECK (
    numero_tentativa >= 1
  ),
  CONSTRAINT envios_campanha_manychat_message_id_nao_vazio CHECK (
    manychat_message_id IS NULL OR LENGTH(TRIM(manychat_message_id)) >= 1
  ),
  CONSTRAINT envios_campanha_status_valido CHECK (
    status IN (
      'pendente',
      'processando',
      'enviado',
      'entregue',
      'lido',
      'respondido',
      'recusado',
      'bloqueado',
      'erro'
    )
  )
);

CREATE TABLE public.respostas_campanha (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  campanha_contato_id BIGINT NOT NULL,
  chave_pergunta VARCHAR(150) NOT NULL,
  resposta TEXT NOT NULL,
  manychat_resposta_id VARCHAR(255),
  respondido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT respostas_campanha_pkey PRIMARY KEY (id),
  CONSTRAINT respostas_campanha_chave_nao_vazia CHECK (
    LENGTH(TRIM(chave_pergunta)) >= 1
  ),
  CONSTRAINT respostas_campanha_resposta_nao_vazia CHECK (
    LENGTH(TRIM(resposta)) >= 1
  ),
  CONSTRAINT respostas_campanha_manychat_resposta_id_nao_vazio CHECK (
    manychat_resposta_id IS NULL OR LENGTH(TRIM(manychat_resposta_id)) >= 1
  )
);

CREATE TABLE public.eventos_manychat (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  identificador_externo VARCHAR(255) NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  status_processamento VARCHAR(30) NOT NULL DEFAULT 'pendente',
  quantidade_tentativas INTEGER NOT NULL DEFAULT 0,
  mensagem_erro TEXT,
  recebido_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processado_em TIMESTAMPTZ,
  CONSTRAINT eventos_manychat_pkey PRIMARY KEY (id),
  CONSTRAINT eventos_manychat_identificador_externo_unico UNIQUE (
    identificador_externo
  ),
  CONSTRAINT eventos_manychat_identificador_nao_vazio CHECK (
    LENGTH(TRIM(identificador_externo)) >= 1
  ),
  CONSTRAINT eventos_manychat_tipo_nao_vazio CHECK (LENGTH(TRIM(tipo)) >= 1),
  CONSTRAINT eventos_manychat_status_valido CHECK (
    status_processamento IN ('pendente', 'processando', 'processado', 'ignorado', 'erro')
  ),
  CONSTRAINT eventos_manychat_tentativas_validas CHECK (
    quantidade_tentativas >= 0
  )
);

CREATE TABLE public.sincronizacoes_manychat (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  contato_id BIGINT,
  campanha_id BIGINT,
  tipo VARCHAR(100) NOT NULL,
  direcao VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pendente',
  quantidade_tentativas INTEGER NOT NULL DEFAULT 0,
  mensagem_erro TEXT,
  iniciada_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finalizada_em TIMESTAMPTZ,
  ultima_sincronizacao_em TIMESTAMPTZ,
  CONSTRAINT sincronizacoes_manychat_pkey PRIMARY KEY (id),
  CONSTRAINT sincronizacoes_manychat_referencia_obrigatoria CHECK (
    contato_id IS NOT NULL OR campanha_id IS NOT NULL
  ),
  CONSTRAINT sincronizacoes_manychat_tipo_nao_vazio CHECK (
    LENGTH(TRIM(tipo)) >= 1
  ),
  CONSTRAINT sincronizacoes_manychat_direcao_valida CHECK (
    direcao IN ('sistema_para_manychat', 'manychat_para_sistema')
  ),
  CONSTRAINT sincronizacoes_manychat_status_valido CHECK (
    status IN ('pendente', 'processando', 'concluida', 'erro')
  ),
  CONSTRAINT sincronizacoes_manychat_tentativas_validas CHECK (
    quantidade_tentativas >= 0
  )
);

CREATE FUNCTION public.contato_pode_receber_campanha(contato_id_consultado BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.contatos AS contato
    WHERE contato.id = contato_id_consultado
      AND contato.bloqueado_para_mensagens = FALSE
      AND contato.bloqueado_para_campanhas = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM public.solicitacoes_exclusao AS solicitacao
        WHERE solicitacao.contato_id = contato.id
          AND solicitacao.status = 'pendente'
      )
      AND EXISTS (
        SELECT 1
        FROM public.consentimentos AS consentimento
        WHERE consentimento.contato_id = contato.id
          AND consentimento.tipo = 'mensagens'
          AND consentimento.ativo = TRUE
          AND consentimento.resposta = TRUE
          AND (
            consentimento.estado = 'autorizado'
            OR consentimento.estado IS NULL
          )
      )
  );
$$;

CREATE FUNCTION public.validar_participacao_campanha()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF public.contato_pode_receber_campanha(NEW.contato_id) = FALSE THEN
    RAISE EXCEPTION
      'Contato não está elegível para campanhas: autorização ausente, revogada ou cadastro bloqueado.'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE FUNCTION public.validar_envio_campanha()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  contato_id_encontrado BIGINT;
  status_participacao VARCHAR(30);
BEGIN
  SELECT participacao.contato_id, participacao.status
  INTO contato_id_encontrado, status_participacao
  FROM public.campanha_contatos AS participacao
  WHERE participacao.id = NEW.campanha_contato_id;

  IF contato_id_encontrado IS NULL THEN
    RAISE EXCEPTION 'Participação na campanha não encontrada.'
      USING ERRCODE = 'foreign_key_violation';
  END IF;

  IF status_participacao IN ('recusado', 'bloqueado', 'concluido') THEN
    RAISE EXCEPTION
      'Novo envio recusado para uma participação finalizada ou bloqueada.'
      USING ERRCODE = 'check_violation';
  END IF;

  IF public.contato_pode_receber_campanha(contato_id_encontrado) = FALSE THEN
    RAISE EXCEPTION
      'Novo envio recusado: contato sem autorização ativa ou com bloqueio.'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE UNIQUE INDEX origens_slug_unico
  ON public.origens (LOWER(slug));

CREATE UNIQUE INDEX bairros_nome_normalizado_unico
  ON public.bairros (LOWER(TRIM(nome)));

CREATE INDEX bairros_ativos_nome_indice
  ON public.bairros (LOWER(nome))
  WHERE ativo = TRUE;

CREATE UNIQUE INDEX usuarios_email_unico
  ON public.usuarios (LOWER(email));

CREATE INDEX usuarios_perfil_indice
  ON public.usuarios (perfil);

CREATE UNIQUE INDEX eventos_apenas_um_ativo
  ON public.eventos (status)
  WHERE status = 'ativo';

CREATE INDEX eventos_periodo_indice
  ON public.eventos (data_inicial, data_final);

CREATE INDEX historico_eventos_evento_id_indice
  ON public.historico_eventos (evento_id, criado_em DESC);

CREATE UNIQUE INDEX contatos_telefone_normalizado_unico
  ON public.contatos (telefone_normalizado);

CREATE INDEX contatos_nome_indice
  ON public.contatos (LOWER(nome));

CREATE INDEX contatos_bairro_indice
  ON public.contatos (LOWER(bairro));

CREATE INDEX contatos_problema_indice
  ON public.contatos (LOWER(problema));

CREATE INDEX contatos_criado_em_indice
  ON public.contatos (criado_em DESC);

CREATE INDEX contatos_consentimento_ligacoes_indice
  ON public.contatos (consentimento_ligacoes);

CREATE INDEX contatos_consentimento_whatsapp_indice
  ON public.contatos (consentimento_whatsapp);

CREATE INDEX contatos_origem_atual_indice
  ON public.contatos (LOWER(origem_atual));

CREATE INDEX contatos_origem_id_indice
  ON public.contatos (origem_id);

CREATE INDEX contatos_status_contato_indice
  ON public.contatos (LOWER(status_contato));

CREATE INDEX contatos_bloqueado_para_campanhas_indice
  ON public.contatos (bloqueado_para_campanhas)
  WHERE bloqueado_para_campanhas = TRUE;

CREATE UNIQUE INDEX contatos_manychat_contact_id_unico
  ON public.contatos (manychat_contact_id)
  WHERE manychat_contact_id IS NOT NULL;

CREATE INDEX contato_eventos_evento_id_indice
  ON public.contato_eventos (evento_id, cadastrado_em DESC);

CREATE INDEX contato_eventos_contato_id_indice
  ON public.contato_eventos (contato_id);

CREATE INDEX consentimentos_contato_id_indice
  ON public.consentimentos (contato_id);

CREATE UNIQUE INDEX consentimentos_contato_tipo_ativo_unico
  ON public.consentimentos (contato_id, tipo)
  WHERE ativo = TRUE;

CREATE INDEX consentimentos_contato_original_indice
  ON public.consentimentos (contato_id_original);

CREATE INDEX consentimentos_registro_anterior_indice
  ON public.consentimentos (registro_anterior_id)
  WHERE registro_anterior_id IS NOT NULL;

CREATE UNIQUE INDEX solicitacoes_exclusao_contato_pendente_unico
  ON public.solicitacoes_exclusao (contato_id)
  WHERE status = 'pendente' AND contato_id IS NOT NULL;

CREATE INDEX solicitacoes_exclusao_status_data_indice
  ON public.solicitacoes_exclusao (status, solicitada_em DESC);

CREATE INDEX consentimentos_criado_em_indice
  ON public.consentimentos (criado_em DESC);

CREATE INDEX consentimentos_estado_indice
  ON public.consentimentos (estado);

CREATE INDEX consentimentos_origem_id_indice
  ON public.consentimentos (origem_id);

CREATE INDEX aceites_privacidade_contato_id_indice
  ON public.aceites_privacidade (contato_id);

CREATE INDEX aceites_privacidade_criado_em_indice
  ON public.aceites_privacidade (criado_em DESC);

CREATE UNIQUE INDEX aceites_privacidade_resposta_identica_unica
  ON public.aceites_privacidade (
    contato_id,
    versao_texto,
    origem_id,
    canal,
    MD5(texto_apresentado)
  )
  WHERE aceito = TRUE;

CREATE INDEX historico_contatos_contato_id_indice
  ON public.historico_contatos (contato_id);

CREATE INDEX historico_contatos_criado_em_indice
  ON public.historico_contatos (criado_em DESC);

CREATE INDEX historico_contatos_origem_id_indice
  ON public.historico_contatos (origem_id);

CREATE INDEX importacoes_criado_em_indice
  ON public.importacoes (criado_em DESC);

CREATE INDEX importacao_linhas_importacao_id_indice
  ON public.importacao_linhas (importacao_id);

CREATE INDEX importacao_linhas_contato_id_indice
  ON public.importacao_linhas (contato_id);

CREATE INDEX tentativas_login_email_data_indice
  ON public.tentativas_login (LOWER(email_informado), criado_em DESC);

CREATE INDEX tentativas_login_ip_data_indice
  ON public.tentativas_login (endereco_ip, criado_em DESC);

CREATE INDEX tentativas_login_usuario_data_indice
  ON public.tentativas_login (usuario_id, criado_em DESC);

CREATE INDEX backups_banco_criado_em_indice
  ON public.backups_banco (criado_em DESC);

CREATE INDEX backups_banco_usuario_id_indice
  ON public.backups_banco (usuario_id)
  WHERE usuario_id IS NOT NULL;

CREATE UNIQUE INDEX textos_formulario_tipo_ativo_unico
  ON public.textos_formulario (tipo)
  WHERE ativo = TRUE;

CREATE INDEX campanhas_status_indice
  ON public.campanhas (status);

CREATE INDEX campanhas_criado_em_indice
  ON public.campanhas (criado_em DESC);

CREATE INDEX campanhas_manychat_flow_id_indice
  ON public.campanhas (manychat_flow_id)
  WHERE manychat_flow_id IS NOT NULL;

CREATE INDEX campanha_contatos_contato_id_indice
  ON public.campanha_contatos (contato_id);

CREATE INDEX campanha_contatos_status_indice
  ON public.campanha_contatos (status);

CREATE INDEX envios_campanha_status_indice
  ON public.envios_campanha (status);

CREATE INDEX envios_campanha_solicitado_em_indice
  ON public.envios_campanha (solicitado_em DESC);

CREATE UNIQUE INDEX envios_campanha_manychat_message_id_unico
  ON public.envios_campanha (manychat_message_id)
  WHERE manychat_message_id IS NOT NULL;

CREATE INDEX respostas_campanha_participacao_indice
  ON public.respostas_campanha (campanha_contato_id);

CREATE UNIQUE INDEX respostas_campanha_manychat_resposta_id_unico
  ON public.respostas_campanha (manychat_resposta_id)
  WHERE manychat_resposta_id IS NOT NULL;

CREATE INDEX eventos_manychat_status_recebimento_indice
  ON public.eventos_manychat (status_processamento, recebido_em);

CREATE INDEX sincronizacoes_manychat_contato_id_indice
  ON public.sincronizacoes_manychat (contato_id)
  WHERE contato_id IS NOT NULL;

CREATE INDEX sincronizacoes_manychat_campanha_id_indice
  ON public.sincronizacoes_manychat (campanha_id)
  WHERE campanha_id IS NOT NULL;

CREATE INDEX sincronizacoes_manychat_status_indice
  ON public.sincronizacoes_manychat (status, iniciada_em);

CREATE TRIGGER origens_atualizar_data
BEFORE UPDATE ON public.origens
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER bairros_atualizar_data
BEFORE UPDATE ON public.bairros
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER usuarios_atualizar_data
BEFORE UPDATE ON public.usuarios
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER eventos_atualizar_data
BEFORE UPDATE ON public.eventos
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER contatos_atualizar_data
BEFORE UPDATE ON public.contatos
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER textos_formulario_atualizar_data
BEFORE UPDATE ON public.textos_formulario
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER campanhas_atualizar_data
BEFORE UPDATE ON public.campanhas
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER campanha_contatos_atualizar_data
BEFORE UPDATE ON public.campanha_contatos
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_modificacao();

CREATE TRIGGER campanha_contatos_validar_inclusao
BEFORE INSERT ON public.campanha_contatos
FOR EACH ROW
EXECUTE FUNCTION public.validar_participacao_campanha();

CREATE TRIGGER campanha_contatos_validar_troca_contato
BEFORE UPDATE OF contato_id ON public.campanha_contatos
FOR EACH ROW
EXECUTE FUNCTION public.validar_participacao_campanha();

CREATE TRIGGER envios_campanha_validar_novo_envio
BEFORE INSERT ON public.envios_campanha
FOR EACH ROW
EXECUTE FUNCTION public.validar_envio_campanha();

ALTER TABLE public.contatos
  ADD CONSTRAINT contatos_bairro_fkey
    FOREIGN KEY (bairro) REFERENCES public.bairros(nome),
  ADD CONSTRAINT contatos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id);

ALTER TABLE public.eventos
  ADD CONSTRAINT eventos_criado_por_usuario_id_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT eventos_atualizado_por_usuario_id_fkey
    FOREIGN KEY (atualizado_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.historico_eventos
  ADD CONSTRAINT historico_eventos_evento_id_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE CASCADE,
  ADD CONSTRAINT historico_eventos_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.contato_eventos
  ADD CONSTRAINT contato_eventos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT contato_eventos_evento_id_fkey
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id);

ALTER TABLE public.consentimentos
  ADD CONSTRAINT consentimentos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL,
  ADD CONSTRAINT consentimentos_registro_anterior_id_fkey
    FOREIGN KEY (registro_anterior_id) REFERENCES public.consentimentos(id),
  ADD CONSTRAINT consentimentos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT consentimentos_registrado_por_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.solicitacoes_exclusao
  ADD CONSTRAINT solicitacoes_exclusao_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL,
  ADD CONSTRAINT solicitacoes_exclusao_solicitante_fkey
    FOREIGN KEY (solicitada_por_usuario_id) REFERENCES public.usuarios(id),
  ADD CONSTRAINT solicitacoes_exclusao_analista_fkey
    FOREIGN KEY (analisada_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.aceites_privacidade
  ADD CONSTRAINT aceites_privacidade_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT aceites_privacidade_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT aceites_privacidade_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.historico_contatos
  ADD CONSTRAINT historico_contatos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT historico_contatos_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT historico_contatos_usuario_id_fkey
    FOREIGN KEY (registrado_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.importacoes
  ADD CONSTRAINT importacoes_origem_id_fkey
    FOREIGN KEY (origem_id) REFERENCES public.origens(id),
  ADD CONSTRAINT importacoes_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.importacao_linhas
  ADD CONSTRAINT importacao_linhas_importacao_id_fkey
    FOREIGN KEY (importacao_id)
    REFERENCES public.importacoes(id)
    ON DELETE CASCADE,
  ADD CONSTRAINT importacao_linhas_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE SET NULL;

ALTER TABLE public.tentativas_login
  ADD CONSTRAINT tentativas_login_usuario_id_fkey
    FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.backups_banco
  ADD CONSTRAINT backups_banco_usuario_id_fkey
    FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.campanhas
  ADD CONSTRAINT campanhas_criado_por_usuario_id_fkey
    FOREIGN KEY (criado_por_usuario_id) REFERENCES public.usuarios(id);

ALTER TABLE public.campanha_contatos
  ADD CONSTRAINT campanha_contatos_campanha_id_fkey
    FOREIGN KEY (campanha_id)
    REFERENCES public.campanhas(id)
    ON DELETE CASCADE,
  ADD CONSTRAINT campanha_contatos_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT campanha_contatos_incluido_por_usuario_id_fkey
    FOREIGN KEY (incluido_por_usuario_id)
    REFERENCES public.usuarios(id)
    ON DELETE SET NULL;

ALTER TABLE public.envios_campanha
  ADD CONSTRAINT envios_campanha_campanha_contato_id_fkey
    FOREIGN KEY (campanha_contato_id)
    REFERENCES public.campanha_contatos(id)
    ON DELETE CASCADE;

ALTER TABLE public.respostas_campanha
  ADD CONSTRAINT respostas_campanha_campanha_contato_id_fkey
    FOREIGN KEY (campanha_contato_id)
    REFERENCES public.campanha_contatos(id)
    ON DELETE CASCADE;

ALTER TABLE public.sincronizacoes_manychat
  ADD CONSTRAINT sincronizacoes_manychat_contato_id_fkey
    FOREIGN KEY (contato_id) REFERENCES public.contatos(id) ON DELETE CASCADE,
  ADD CONSTRAINT sincronizacoes_manychat_campanha_id_fkey
    FOREIGN KEY (campanha_id) REFERENCES public.campanhas(id);

COMMENT ON TABLE public.contatos IS
  'Pessoas cadastradas por meio do formulário público.';

COMMENT ON COLUMN public.contatos.telefone IS
  'Telefone no formato informado pela pessoa.';

COMMENT ON COLUMN public.contatos.telefone_normalizado IS
  'Telefone contendo somente números, utilizado para impedir duplicidade.';

COMMENT ON COLUMN public.contatos.problema IS
  'Categoria do problema. A coluna foi preservada por compatibilidade.';

COMMENT ON COLUMN public.contatos.consentimento_armazenamento IS
  'Indica autorização para armazenamento dos dados. Deve ser verdadeiro para existir cadastro.';

COMMENT ON COLUMN public.contatos.consentimento_mensagens IS
  'Indica se a pessoa autorizou mensagens futuras.';

COMMENT ON COLUMN public.contatos.consentimento_armazenamento_em IS
  'Data e hora em que o consentimento para armazenamento foi registrado.';

COMMENT ON COLUMN public.contatos.consentimento_mensagens_em IS
  'Data e hora da autorização para mensagens futuras. Fica nulo quando não autorizado.';

COMMENT ON COLUMN public.contatos.idade IS
  'Idade informada no cadastro. Registros legados permanecem NULL.';

COMMENT ON COLUMN public.contatos.descricao_problema IS
  'Descrição opcional complementar à categoria do problema.';

COMMENT ON TABLE public.usuarios IS
  'Usuários internos autorizados a acessar o painel administrativo.';

COMMENT ON TABLE public.bairros IS
  'Catálogo oficial dos bairros do município do Rio de Janeiro usado por todos os cadastros.';

COMMENT ON COLUMN public.contatos.bairro IS
  'Nome canônico validado pelo catálogo public.bairros.';

COMMENT ON COLUMN public.usuarios.senha_hash IS
  'Hash da senha gerado pela aplicação com bcrypt. Nunca armazenar senha em texto puro.';

-- Configurações técnicas necessárias para o backend operar em um banco novo.
-- Não há dados pessoais nestes registros.
-- Fonte: camada Limite de Bairros da Prefeitura da Cidade do Rio de Janeiro,
-- acrescida do bairro Argentino, criado pela Lei Municipal nº 8.020/2025.
INSERT INTO public.bairros (nome)
VALUES
  ('Abolição'),
  ('Acari'),
  ('Água Santa'),
  ('Alto da Boa Vista'),
  ('Anchieta'),
  ('Andaraí'),
  ('Anil'),
  ('Argentino'),
  ('Bancários'),
  ('Bangu'),
  ('Barra da Tijuca'),
  ('Barra de Guaratiba'),
  ('Barra Olímpica'),
  ('Barros Filho'),
  ('Benfica'),
  ('Bento Ribeiro'),
  ('Bonsucesso'),
  ('Botafogo'),
  ('Brás de Pina'),
  ('Cachambi'),
  ('Cacuia'),
  ('Caju'),
  ('Camorim'),
  ('Campinho'),
  ('Campo dos Afonsos'),
  ('Campo Grande'),
  ('Cascadura'),
  ('Catete'),
  ('Catumbi'),
  ('Cavalcanti'),
  ('Centro'),
  ('Cidade de Deus'),
  ('Cidade Nova'),
  ('Cidade Universitária'),
  ('Cocotá'),
  ('Coelho Neto'),
  ('Colégio'),
  ('Complexo do Alemão'),
  ('Copacabana'),
  ('Cordovil'),
  ('Cosme Velho'),
  ('Cosmos'),
  ('Costa Barros'),
  ('Curicica'),
  ('Del Castilho'),
  ('Deodoro'),
  ('Encantado'),
  ('Engenheiro Leal'),
  ('Engenho da Rainha'),
  ('Engenho de Dentro'),
  ('Engenho Novo'),
  ('Estácio'),
  ('Flamengo'),
  ('Freguesia (Ilha)'),
  ('Freguesia (Jacarepaguá)'),
  ('Galeão'),
  ('Gamboa'),
  ('Gardênia Azul'),
  ('Gávea'),
  ('Gericinó'),
  ('Glória'),
  ('Grajaú'),
  ('Grumari'),
  ('Guadalupe'),
  ('Guaratiba'),
  ('Higienópolis'),
  ('Honório Gurgel'),
  ('Humaitá'),
  ('Ilha de Guaratiba'),
  ('Inhaúma'),
  ('Inhoaíba'),
  ('Ipanema'),
  ('Irajá'),
  ('Itanhangá'),
  ('Jabour'),
  ('Jacaré'),
  ('Jacarepaguá'),
  ('Jacarezinho'),
  ('Jardim América'),
  ('Jardim Botânico'),
  ('Jardim Carioca'),
  ('Jardim Guanabara'),
  ('Jardim Sulacap'),
  ('Joá'),
  ('Lagoa'),
  ('Lapa'),
  ('Laranjeiras'),
  ('Leblon'),
  ('Leme'),
  ('Lins de Vasconcelos'),
  ('Madureira'),
  ('Magalhães Bastos'),
  ('Mangueira'),
  ('Manguinhos'),
  ('Maracanã'),
  ('Maré'),
  ('Marechal Hermes'),
  ('Maria da Graça'),
  ('Méier'),
  ('Moneró'),
  ('Olaria'),
  ('Osvaldo Cruz'),
  ('Paciência'),
  ('Padre Miguel'),
  ('Paquetá'),
  ('Parada de Lucas'),
  ('Parque Anchieta'),
  ('Parque Colúmbia'),
  ('Pavuna'),
  ('Pechincha'),
  ('Pedra de Guaratiba'),
  ('Penha'),
  ('Penha Circular'),
  ('Piedade'),
  ('Pilares'),
  ('Pitangueiras'),
  ('Portuguesa'),
  ('Praça da Bandeira'),
  ('Praça Seca'),
  ('Praia da Bandeira'),
  ('Quintino Bocaiúva'),
  ('Ramos'),
  ('Realengo'),
  ('Recreio dos Bandeirantes'),
  ('Riachuelo'),
  ('Ribeira'),
  ('Ricardo de Albuquerque'),
  ('Rio Comprido'),
  ('Rocha'),
  ('Rocha Miranda'),
  ('Rocinha'),
  ('Sampaio'),
  ('Santa Cruz'),
  ('Santa Teresa'),
  ('Santíssimo'),
  ('Santo Cristo'),
  ('São Conrado'),
  ('São Cristóvão'),
  ('São Francisco Xavier'),
  ('Saúde'),
  ('Senador Camará'),
  ('Senador Vasconcelos'),
  ('Sepetiba'),
  ('Tanque'),
  ('Taquara'),
  ('Tauá'),
  ('Tijuca'),
  ('Todos os Santos'),
  ('Tomás Coelho'),
  ('Turiaçú'),
  ('Urca'),
  ('Vargem Grande'),
  ('Vargem Pequena'),
  ('Vasco da Gama'),
  ('Vaz Lobo'),
  ('Vicente de Carvalho'),
  ('Vidigal'),
  ('Vigário Geral'),
  ('Vila da Penha'),
  ('Vila Isabel'),
  ('Vila Kennedy'),
  ('Vila Kosmos'),
  ('Vila Militar'),
  ('Vila Valqueire'),
  ('Vista Alegre'),
  ('Zumbi');

INSERT INTO public.origens (nome, slug, tipo, ativa)
VALUES
  ('Formulário público', 'formulario-publico', 'formulario', TRUE),
  ('Cadastro manual', 'cadastro-manual', 'manual', TRUE);

INSERT INTO public.textos_formulario (tipo, versao, texto)
VALUES
  (
    'aviso_privacidade',
    'aviso_privacidade_v1',
    'Li o Aviso de Privacidade e autorizo o tratamento dos dados informados para participação no projeto A Voz do Bairro.'
  ),
  (
    'mensagens',
    'mensagens_v1',
    'Autorizo o recebimento de futuras mensagens sobre ações sociais, projetos comunitários, pesquisas, conteúdos políticos, eventos e iniciativas relacionadas à melhoria dos bairros.'
  ),
  (
    'ligacoes',
    'ligacoes_v1',
    'Autorizo o recebimento de futuras ligações sobre ações sociais, projetos comunitários, pesquisas, conteúdos políticos, eventos e iniciativas relacionadas à melhoria dos bairros.'
  );

COMMIT;
