const LIMITE_LINHAS = 20000;
const LIMITE_ARQUIVO_BYTES = 5 * 1024 * 1024;
const LIMITE_ARQUIVO_MEGABYTES = 5;
const TAMANHO_LOTE = 500;
const CHAVE_BLOQUEIO_1 = 1098274;
const CHAVE_BLOQUEIO_2 = 1;

module.exports = {
  LIMITE_LINHAS,
  LIMITE_ARQUIVO_BYTES,
  LIMITE_ARQUIVO_MEGABYTES,
  TAMANHO_LOTE,
  CHAVE_BLOQUEIO_1,
  CHAVE_BLOQUEIO_2
};
